### ISSUE TITLE
Testing：No such file or directory: './resnet50_ft_weight.pkl'

### ISSUE THREAD

**Issue by grass-s** [huangzhikun1995/IPM-Net#2]
IPM-Net/utils.py:95: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(stream)
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    trainer = IPMNet_Trainer(config)
  File "/home/rov/workspace/python/IPM-Net/trainer.py", line 48, in __init__
    self.vgg = load_resnet50(vgg_weight_file)
  File "/home/rov/workspace/python/IPM-Net/utils.py", line 216, in load_resnet50
    load_state_dict(model, model_dir)
  File "/home/rov/workspace/python/IPM-Net/utils.py", line 393, in load_state_dict
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './resnet50_ft_weight.pkl'

**Comment by huangzhikun1995** [comment]
I added the download link of this model in README.m, please try again.  Thank you.
